Repository fabiencelier/universions, pull requests merged in 2019-11, with the labels that each got.

#18 Add Python 3.8 in tests
  .github/workflows/test.yaml
  Pipfile
  Pipfile.lock
  setup.py
Labels: :gear: Automation

#20 Add sphinx documentation
  .gitignore
  Pipfile
  Pipfile.lock
  RELEASE.md
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install.rst
  docs/source/pydoc/modules.rst
  docs/source/pydoc/universions.java.rst
  docs/source/pydoc/universions.node.rst
  docs/source/pydoc/universions.rst
  docs/source/supported.rst
  docs/source/tools/node.rst
Labels: documentation

#21 Add master_doc = 'index' for readthedocs
  docs/source/conf.py
Labels: documentation

#25 Add github actions for deployment
  .github/workflows/continousous-deployment.yaml
  scripts/__pycache__/update_version.cpython-37.pyc
  scripts/check.sh
  scripts/release.py
  scripts/update_version.py
  universions/_version.py
Labels: :gear: Automation

#31 Add windows in the test CI
  .github/workflows/test.yaml
Labels: :gear: Automation

#16 Add cli tool.
  scripts/check.sh
  setup.py
  universions/__init__.py
  universions/cli.py
  universions/node/__init__.py
Labels: :computer: CLI

#35 Add Macos to CI tests
  .github/workflows/test.yaml
  test/test_cli.py
Labels: :gear: Automation

#36 Add isort and sort all imports
  .github/workflows/test.yaml
  .isort.cfg
  Pipfile
  Pipfile.lock
  scripts/check.sh
  scripts/release.py
  scripts/update_version.py
  setup.py
  test/mock_popen.py
  test/test_java_version.py
  test/test_node_version.py
  test/test_semver_parser.py
  universions/__init__.py
  universions/_exec.py
  universions/cli.py
  universions/java/__init__.py
  universions/node/__init__.py
  universions/version.py
Labels: :gear: Automation

#38 Add black badge
  README.md
Labels: :scroll: documentation

#40 Remove pkg_resources dependecy, add CLI verbosity test
  test/test_cli.py
  universions/cli.py
Labels: :bug: bug

#43 Add example in doc
  README.md
Labels: :scroll: documentation

#45 Add python as a supported tool
  README.md
  docs/source/tools/node.rst
  scripts/format.sh
  test/test_node_version.py
  test/test_python.py
  universions/cli.py
  universions/node/__init__.py
  universions/python/__init__.py
  universions/python/_parser.py
Labels: :sparkles: new tool

#46 Add release script on tag
  .github/workflows/release-deployment.yaml
  scripts/release.py
  scripts/update_version.py
Labels: :gear: Automation

#52 Support for pip
  README.md
  test/test_pip_version.py
  universions/cli.py
  universions/pip/__init__.py
Labels: :sparkles: new tool

#53 Add an --all option in the CLI
  test/test_cli.py
  universions/_exec.py
  universions/cli.py
  universions/error.py
  universions/java/__init__.py
Labels: :computer: CLI

#34 Add support for git knowing only mac output.
  .gitignore
  README.md
  docs/source/tools/git.rst
  test/test_git_version.py
  universions/cli.py
  universions/git/__init__.py
Labels: :sparkles: new tool

#58 Add cli path option
  universions/cli.py
Labels: :computer: CLI

#57 Trying using cache for the actions
  .github/workflows/test.yaml
Labels: :gear: Automation

#60 Add cli tests
  test/fake-node.sh
  test/test_cli.py
Labels: :computer: CLI

#33 Add support for npm.
  README.md
  docs/source/tools/npm.rst
  test/test_npm_version.py
  universions/cli.py
  universions/npm/__init__.py
Labels: :sparkles: new tool

#62 Fix the comparaison, pre < stable and None does not fail.
  test/test_comparaison.py
  test/test_version_type.py
  universions/version.py
Labels: :bug: bug
